
BUILD_DIR = ../../Build

$(BUILD_DIR)/linked_list: linked_list.c
	gcc -Wall -o $(BUILD_DIR)/linked_list linked_list.c

linked_list:
	gcc -Wall -g -o $(BUILD_DIR)/linked_list -O2 linked_list.c

all: linked_list


